server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
#    url: ${DATABASE_URL}
    username: postgres
#    username: ${DATABASE_USERNAME)
    password: my-secret-pw
#    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
  output:
    ansi:
      enabled: always


#  datasource:
#    url: jdbc:h2:mem:blog
#    username: fprh13
#    password: super-h2-pw
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug

#  x-nxopen-api-key
nexon:
  key: ${NEXON_KEY}
  url : ${NEXON_URL}

